// Messages
export const SEND_VERIFICATION_EMAIL = "SEND_VERIFICATION_EMAIL"

export const SEND_FORGOT_PASSWORD_EMAIL = "SEND_FORGOT_PASSWORD_EMAIL"
export const SEND_SETUP_PASSWORD_EMAIL = "SEND_SETUP_PASSWORD_EMAIL"

export const SEND_WELCOME_EMAIL = "SEND_WELCOME_EMAIL"

export const SEND_PRINT_JOB = "SEND_PRINT_JOB"

export const SEND_LOGIN_SUCCESS_EMAIL = "SEND_LOGIN_SUCCESS_EMAIL";

export const SEND_JOB_CREATED_EMAIL = "SEND_JOB_CREATED_EMAIL";

export const SEND_JOB_SENT_EMAIL = "SEND_JOB_SENT_EMAIL";

export const SEND_JOB_FAILED_EMAIL = "SEND_JOB_FAILED_EMAIL";

export const SEND_JOB_QUEUED_EMAIL = "SEND_JOB_QUEUED_EMAIL";

export const SEND_PAYMENT_INITIATED_EMAIL = "SEND_PAYMENT_INITIATED_EMAIL";

export const SEND_PAYMENT_SUCCEEDED_EMAIL = "SEND_PAYMENT_SUCCEEDED_EMAIL";

export const SEND_ADMIN_CREDIT_ADDED_EMAIL = "SEND_ADMIN_CREDIT_ADDED_EMAIL";

export const SEND_PAYMENT_FAILED_EMAIL = "SEND_PAYMENT_FAILED_EMAIL";

export const SEND_AUTO_CHARGE_TRIGGERED_EMAIL = "SEND_AUTO_CHARGE_TRIGGERED_EMAIL";

export const SEND_2FA_CODE_EMAIL = "SEND_2FA_CODE_EMAIL";

export const SEND_PHONE_VERIFICATION_EMAIL = "SEND_PHONE_VERIFICATION_EMAIL";

export const SEND_USER_APPROVAL_REQUEST = "SEND_USER_APPROVAL_REQUEST";

export const SEND_USER_APPROVAL_RESPONSE = "SEND_USER_APPROVAL_RESPONSE";

export const SEND_UNVERIFIED_COMPANY_WARNING = "SEND_UNVERIFIED_COMPANY_WARNING";

export const SEND_CONTACT_ADMIN_EMAIL = 'SEND_CONTACT_ADMIN_EMAIL';

export const SEND_JOB_DELLIVERED_EMAIL = "SEND_JOB_DELLIVERED_EMAIL";